# add user and group
- name: add nagios command group
  group:
    name: nagcmd
    state: present

- name: add nagios user
  user:
    name: nagios
    shell: /bin/bash
    groups: nagcmd

# install packages
- name: install apache webserver
  apt:
    name: ["apache2", "apache2-utils", "php"]
    state: present

# ignore errors in check mode, since --check will otherwise fail at first run
- name: enable modules in apache
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - rewrite
    - cgi
  notify: nagios apache2 restart
  ignore_errors: "{{ ansible_check_mode }}"

- name: put www-data in nagcmd group
  user:
    name: www-data
    groups: nagcmd
    append: yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: install general tools
  apt:
    name: ["wget", "unzip", "python-passlib"]
    state: present

- name: "create local cache dir ({{local_cache_dir}})"
  connection: local
  become: no
  file:
    state: directory
    path: "{{ local_cache_dir }}"

- name: create nagios dir
  file:
    state: directory
    path: "{{ nagios_opt_dir }}"
